name: "FieldCompare"
description: "Compare the fields in two files or two folders of files"
inputs:
  result:
    description: "The file/folder with the results to compare."
    required: True
  reference:
    description: "The file/folder with the references to compare the results against."
    required: True
  tolerance-options:
    description: "Pass the fieldcompare tolerance options as string, e.g. '-rtol 1e-6 -rtol pressure:1e-3 -atol 1e-8 -atol pressure:1e-3'."
    required: False
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.result }}
    - ${{ inputs.reference }}
    - ${{ inputs.tolerance-options }}
